### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [SpigotPE-Team/SpigotAuth#1]
15:32:41 [ERROR] 폴더 '/root/pmmp/plugins/'에서 플러그인 '/root/pmmp/plugins/SpigotAuth-master'을(를) 로드하지 못했습니 다: Argument 2 passed to pocketmine\permission\Permission::loadPermission() must be of the type array, null given, called in /root/pmmp/src/pocketmine/permission/Permission.php on line 207
15:32:41 [CRITICAL] TypeError: "Argument 2 passed to pocketmine\permission\Permission::loadPermission() must be of the type array, null given, called in /root/pmmp/src/pocketmine/permission/Permission.php on line 207" (EXCEPTION) in "/src/pocketmine/permission/Permission" at line 223

**Comment by Asuna-Yuuki** [comment]
Uhh yeah it's not done
